refactor(countdown): rename css
raxjs/rax-components pull request #295
Opened 2020-09-30 03:18 UTC by ChrisCindy

2020-09-30 03:27 UTC, SoloJiang approved these changes

2020-09-30 03:28 UTC, imsobear requested changes

2020-09-30 03:28 UTC, imsobear commented on packages/rax-countdown/src/index.js
> +  return <View className="rax-countdown-item" style={{...timeWrapStyle}}>
这里不需要解构吧

2020-09-30 03:28 UTC, imsobear commented on packages/rax-countdown/src/index.js
> +        <Image className="rax-countdown-background" source={timeBackground} style={{...timeBackgroundStyle}} /> :
同上

2020-09-30 03:28 UTC, imsobear commented on packages/rax-countdown/src/index.js
> +  return <View className="rax-countdown-item" style={{...timeWrapStyle}}>
同时用 classname 和 style 有没有问题

2020-09-30 03:28 UTC, chenjun1011 approved these changes

2020-09-30 04:17 UTC, ChrisCindy commented on packages/rax-countdown/src/index.js
> +  return <View className="rax-countdown-item" style={{...timeWrapStyle}}>
解构问题已修复。同时用 classname 和 style 是可行的，style 由用户传递，覆盖默认配置

2020-10-09 03:20 UTC, imsobear approved these changes

2020-10-09 06:03 UTC, merged