fea: support multiple miniapp
raxjs/rax-components pull request #367
Opened 2021-05-26 06:53 UTC by ChrisCindy

- [x] 支持字节、百度、快手小程序 

- [x] 将 web、weex、小程序代码分离，配置 exports 字段实现跨端规范

2021-05-31 03:45 UTC, SoloJiang requested changes

2021-05-31 03:45 UTC, SoloJiang commented on packages/rax-embed/src/miniapp/index.tsx
> +const defaultProps: Props = {
这个配置在小程序里是不是不需要了

2021-05-31 03:45 UTC, SoloJiang commented on packages/rax-scrollview/src/utils/wrapper.ts
> +export default function wrapper(scrollview: ForwardRefExoticComponent<ScrollViewProps>): ForwardRefExoticComponent<ScrollViewProps> {
传进来的 scrollview 应该首字母大写？wrapper 是不是可以名字语义化点？

2021-05-31 03:45 UTC, SoloJiang commented on packages/rax-waterfall/__tests__/Waterfall.js
> +import Waterfall from '../src/index';
单测感觉有的是从 lib 引入，有的是从 src 引入

2021-05-31 06:04 UTC, SoloJiang commented on packages/rax-view/src/index.tsx
> +let View = null;
需要考虑下小程序 webview

2021-06-22 06:52 UTC, SoloJiang commented on packages/rax-view/src/index.tsx
> +} else if (isMiniApp) {
这里只有 miniapp?

2021-06-23 09:01 UTC, cryzzchen commented on packages/rax-embed/src/web/index.tsx
> +        type=""
看了一下其他的代码看起来是为了统一~

2021-06-23 09:08 UTC, cryzzchen commented on packages/rax-image/src/miniapp/index.tsx
> +  const nativeProps: ImageNativeProps = otherProps as any;
其他组件里面，剩余属性都命名为 rest，统一一下？

2021-06-23 10:15 UTC, chenjun1011 approved these changes

2021-06-23 11:30 UTC, fyangstudio commented on packages/rax-view/src/common/index.tsx
> +    return <div {...rest} onAppear={handleAppear} ref={ref} className={cx( isWeex ? '' : 'rax-view-v2', className)} style={style} />;
微信小程序 也用 div ？

2021-06-24 06:23 UTC, ChrisCindy commented on packages/rax-view/src/index.tsx
> +} else if (isMiniApp) {
是的，之前就是这样的。本地 pr 不作逻辑修改。

2021-06-24 06:28 UTC, ChrisCindy commented on packages/rax-video/src/weex/index.tsx
> +        {...common}
本次 pr 暂不作逻辑修改

2021-06-24 06:33 UTC, ChrisCindy commented on packages/rax-view/src/common/index.tsx
> +    return <div {...rest} onAppear={handleAppear} ref={ref} className={cx( isWeex ? '' : 'rax-view-v2', className)} style={style} />;
是的，目前微信中是直接使用 div

2021-06-24 06:34 UTC, SoloJiang approved these changes

2021-06-24 07:24 UTC, merged